spring:
  servlet:
    multipart:
      max-file-size: 2MB        # 单个文件最大大小
      max-request-size: 10MB    # 总请求最大大小
  datasource:
    url: jdbc:mysql://localhost:3306/second_hand_trading_platform
    username: root
    password: hexu0629
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      connect-timeout: 5000
      client-type: lettuce

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 确保是 true（默认就是 true）开启驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

#接口文档工具
knife4j:
  enable: true  # 开启增强功能
  production: false # 生产环境请设为 true 以关闭文档

server:
  port: 8080

# 自定义文件存储配置
upload:
  # 头像存储路径，根据你的系统改成合适的位置，如 Linux 下的 /var/uploads/avatars/
  path: D:\\DevProjects\\static