spring:
  datasource:
    url: jdbc:mysql://localhost:3306/second_hand_trading_platform
    username: root
    password: hexu0629
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      connect-timeout: 5000
      client-type: lettuce

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl